<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Bolt</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#statement</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.bolt</string>
            <key>match</key>
            <string>\b(if|else|for|return|break|continue|do|then)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.bolt</string>
            <key>match</key>
            <string>(\+|-|\*|/)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.other.bolt</string>
            <key>match</key>
            <string>(&gt;|&gt;=|&lt;|&lt;=|=|==|=&gt;|\!=|\?\?)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.bolt</string>
            <key>match</key>
            <string>(\.|,|:|\!|\?|\?\.)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.other.bolt</string>
            <key>match</key>
            <string>\b(fn|import|from|as|export|type|typeof|let|const|final|unsealed|enum|in|by|to|and|or|not|is|match)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
            <key>match</key>
            <string>\b(any|number|string|bool|array|table|module|Type)\b</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.bolt</string>
            <key>match</key>
            <string>\d[\d_]*(\.[\d_]+)?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.bolt</string>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter.bolt</string>
            <key>match</key>
            <string>\bthis\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.other.array.bolt</string>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.bolt</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.bolt</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>variable.bolt</string>
        <key>match</key>
        <string>\b(@|_|\w)(@|_|\w|\d)*\b</string>
      </dict>
      <key>code-block</key>
      <dict>
        <key>name</key>
        <string>meta.block.bolt</string>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#statement</string>
          </dict>
        </array>
      </dict>
      <key>statement</key>
      <dict>
        <key>name</key>
        <string>meta.statement.bolt</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>name</key>
        <string>meta.expression.bolt</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.bolt</string>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>\n</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.bolt</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.bolt</string>
  </dict>
</plist>